name: Prepare Release

on:
  workflow_dispatch:
    inputs:
      version:
        description: 'New version number (e.g., 1.5.5)'
        required: true

jobs:
  update-version:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Update version in files
      run: |
        VERSION=${{ github.event.inputs.version }}
        
        # Update ultra-vehicle-card.js
        sed -i "s/setVersion('.*')/setVersion('V$VERSION')/" ultra-vehicle-card.js
        
        # Increment the import version
        IMPORT_VERSION=$(grep -oP "version\.js\?v=\K\d+" ultra-vehicle-card.js)
        NEW_IMPORT_VERSION=$((IMPORT_VERSION + 1))
        sed -i "s/version\.js?v=$IMPORT_VERSION/version.js?v=$NEW_IMPORT_VERSION/" ultra-vehicle-card.js
        
        # Update other files
        for file in ultra-vehicle-card-editor.js localize.js; do
          sed -i "s/version\.js?v=$IMPORT_VERSION/version.js?v=$NEW_IMPORT_VERSION/" $file
        done

    - name: Create Pull Request
      uses: peter-evans/create-pull-request@v3
      with:
        title: Prepare release ${{ github.event.inputs.version }}
        body: |
          This PR updates the version number to ${{ github.event.inputs.version }} and increments the import version.
          Please review and merge this PR before creating the release.
        branch: prepare-release-${{ github.event.inputs.version }}
        base: main
